Repository OpenGamma/Strata, pull requests merged in 2018-05, with the labels that each got.

#1677 Combined curve
  modules/market/src/main/java/com/opengamma/strata/market/curve/AddFixedCurve.java
  modules/market/src/main/java/com/opengamma/strata/market/curve/CombinedCurve.java
  modules/market/src/main/java/com/opengamma/strata/market/curve/Curve.java
  modules/market/src/test/java/com/opengamma/strata/market/curve/AddFixedCurveTest.java
  modules/market/src/test/java/com/opengamma/strata/market/curve/CombinedCurveTest.java
Labels: Status:InReview, Type:Enhancement

#1676 Combine map-based futures
  modules/collect/src/main/java/com/opengamma/strata/collect/Guavate.java
  modules/collect/src/test/java/com/opengamma/strata/collect/GuavateTest.java
Labels: Status:InReview

#1679 Update dependencies
  modules/pom.xml
Labels: Status:InReview

#1680 Gamma calculation with combined curve
  modules/pricer/src/main/java/com/opengamma/strata/pricer/sensitivity/CurveGammaCalculator.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/datasets/RatesProviderDataSets.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/sensitivity/CurveGammaCalculatorCrossGammaTest.java
Labels: Status:InReview, Type:Enhancement

#1678 Use Ibor calendar for OIS-Ibor swaps
  modules/product/src/main/java/com/opengamma/strata/product/swap/type/ImmutableOvernightIborSwapConvention.java
  modules/product/src/main/java/com/opengamma/strata/product/swap/type/StandardOvernightIborSwapConventions.java
  modules/product/src/test/java/com/opengamma/strata/product/swap/type/OvernightIborSwapConventionsTest.java
Labels: Status:InReview

#1699 Gamma calculation for legal entity discounting curves
  modules/pricer/src/main/java/com/opengamma/strata/pricer/sensitivity/CurveGammaCalculator.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/datasets/RatesProviderDataSets.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/sensitivity/CurveGammaCalculatorCrossGammaTest.java
Labels: Type:Enhancement

#1703 Jacobian in credit curve
  modules/pricer/src/main/java/com/opengamma/strata/pricer/credit/IsdaCompliantCreditCurveCalibrator.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/credit/FastCreditCurveCalibratorTest.java
Labels: Type:Bug
