Repository OpenGamma/Strata, pull requests merged in 2020-09, with the labels that each got.

#2210 Support complex date sequences
  modules/basics/src/main/java/com/opengamma/strata/basics/date/DateSequence.java
  modules/basics/src/main/java/com/opengamma/strata/basics/date/DateSequences.java
  modules/basics/src/main/java/com/opengamma/strata/basics/date/SequenceDate.java
  modules/basics/src/main/java/com/opengamma/strata/basics/date/StandardDateSequences.java
  modules/basics/src/test/java/com/opengamma/strata/basics/date/DateSequenceTest.java
  modules/basics/src/test/java/com/opengamma/strata/basics/date/SequenceDateTest.java
Labels: Type:Enhancement

#2214 Check calculated rate is not NaN
  modules/pricer/src/main/java/com/opengamma/strata/pricer/impl/rate/DispatchingRateComputationFn.java
Labels: Type:Enhancement

#2216 Add overnight futures to calibration
  modules/pricer/src/main/java/com/opengamma/strata/pricer/curve/CalibrationMeasures.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/curve/MarketQuoteMeasure.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/curve/PresentValueCalibrationMeasure.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/curve/TradeCalibrationMeasure.java
Labels: Type:Enhancement

#2215 Add SGD-SORA index
  modules/basics/src/main/resources/META-INF/com/opengamma/strata/config/base/FloatingRateNameData.ini
  modules/basics/src/main/resources/META-INF/com/opengamma/strata/config/base/OvernightIndexData.csv
  modules/basics/src/test/java/com/opengamma/strata/basics/index/FloatingRateNamesTest.java
  modules/basics/src/test/java/com/opengamma/strata/basics/index/OvernightIndexTest.java
Labels: Type:Enhancement

#2227 Clarify documentation of future contract specs
  modules/product/src/main/java/com/opengamma/strata/product/index/type/IborFutureContractSpec.java
  modules/product/src/main/java/com/opengamma/strata/product/index/type/OvernightFutureContractSpec.java
Labels: Type:Task, auto-merge

#2228 Add support for creating positions to interest rate future conventions.
  modules/product/src/main/java/com/opengamma/strata/product/index/type/IborFutureContractSpec.java
  modules/product/src/main/java/com/opengamma/strata/product/index/type/ImmutableIborFutureContractSpec.java
  modules/product/src/main/java/com/opengamma/strata/product/index/type/ImmutableOvernightFutureContractSpec.java
  modules/product/src/main/java/com/opengamma/strata/product/index/type/OvernightFutureContractSpec.java
  modules/product/src/test/java/com/opengamma/strata/product/index/type/IborFutureContractSpecTest.java
  modules/product/src/test/java/com/opengamma/strata/product/index/type/OvernightFutureContractSpecTest.java
Labels: Type:Enhancement, auto-merge

#2234 Change class loader
  modules/collect/src/main/java/com/opengamma/strata/collect/io/ResourceLocator.java
Labels: Type:Bug
