Repository OpenGamma/Strata, pull requests merged in 2020-10, with the labels that each got.

#2239 Fix Hungarian working Saturdays for 2020
  modules/basics/src/main/resources/com/opengamma/strata/basics/date/GlobalHolidayCalendars.bin
Labels: Type:Bug, auto-merge

#2240 Add constants for StandardId schemes
  examples/src/main/java/com/opengamma/strata/examples/finance/SwapTradeExample.java
  modules/basics/src/main/java/com/opengamma/strata/basics/StandardSchemes.java
  modules/basics/src/test/java/com/opengamma/strata/basics/StandardSchemesTest.java
  modules/loader/src/main/java/com/opengamma/strata/loader/LoaderUtils.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/PositionCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/SensitivityCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/TradeCsvLoader.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/PositionCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/SensitivityCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/TradeCsvLoaderTest.java
  modules/market/src/main/java/com/opengamma/strata/market/observable/IndexQuoteId.java
  modules/product/src/main/java/com/opengamma/strata/product/etd/EtdIdUtils.java
  modules/product/src/test/java/com/opengamma/strata/product/SimpleLegalEntityTest.java
  modules/product/src/test/java/com/opengamma/strata/product/etd/EtdIdUtilsTest.java
  modules/report/src/test/java/com/opengamma/strata/report/framework/expression/PositionTokenEvaluatorTest.java
Labels: Type:Enhancement

#2241 Preserve order in MapStream::toMapGrouping
  modules/collect/src/main/java/com/opengamma/strata/collect/MapStream.java
  modules/collect/src/test/java/com/opengamma/strata/collect/MapStreamTest.java
Labels: Type:Bug

#2242 Better error message for inflation curve node
  modules/market/src/main/java/com/opengamma/strata/market/curve/InflationNodalCurve.java
Labels: auto-merge
