Repository OpenGamma/Strata, pull requests merged in 2021-09, with the labels that each got.

#2351 AdjustableDates and Guavate
  modules/basics/src/main/java/com/opengamma/strata/basics/date/AdjustableDates.java
  modules/basics/src/test/java/com/opengamma/strata/basics/date/AdjustableDatesTest.java
  modules/collect/src/main/java/com/opengamma/strata/collect/Guavate.java
  modules/collect/src/test/java/com/opengamma/strata/collect/GuavateTest.java
Labels: auto-merge

#2352 Increase schedule flexibility
  modules/basics/src/main/java/com/opengamma/strata/basics/schedule/PeriodicSchedule.java
  modules/basics/src/main/java/com/opengamma/strata/basics/schedule/StubConvention.java
  modules/basics/src/test/java/com/opengamma/strata/basics/schedule/PeriodicScheduleTest.java
  modules/basics/src/test/java/com/opengamma/strata/basics/schedule/StubConventionTest.java
Labels: Type:Enhancement

#2353 Replace start date in schedule
  modules/basics/src/main/java/com/opengamma/strata/basics/schedule/PeriodicSchedule.java
  modules/basics/src/main/java/com/opengamma/strata/basics/schedule/StubConvention.java
  modules/basics/src/test/java/com/opengamma/strata/basics/schedule/PeriodicScheduleTest.java
  modules/basics/src/test/java/com/opengamma/strata/basics/schedule/StubConventionTest.java
Labels: Type:Enhancement

#2355 Fix time-series merge to correctly handle weekends
  modules/collect/src/main/java/com/opengamma/strata/collect/timeseries/LocalDateDoubleTimeSeriesBuilder.java
  modules/collect/src/test/java/com/opengamma/strata/collect/timeseries/DenseLocalDateDoubleTimeSeriesTest.java
Labels: Type:Bug

#2356 Enhance IborCapFloorTrade pricer
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/IborCapletFloorletPeriodAmounts.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/VolatilityIborCapFloorLegPricer.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/VolatilityIborCapFloorProductPricer.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/VolatilityIborCapFloorTradePricer.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/VolatilityIborCapletFloorletPeriodPricer.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/BlackIborCapFloorLegPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/BlackIborCapFloorProductPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/BlackIborCapFloorTradePricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/BlackIborCapletFloorletPeriodPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/IborCapletFloorletPeriodAmountsTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/SabrIborCapFloorLegPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/SabrIborCapFloorProductPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/SabrIborCapFloorTradePricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/SabrIborCapletFloorletPeriodPricerTest.java
Labels: Type:Enhancement, auto-merge

#2354 Swaption Bermudan/American exercise
  modules/basics/src/main/java/com/opengamma/strata/basics/date/AdjustableDates.java
  modules/product/src/main/java/com/opengamma/strata/product/swap/KnownAmountSwapLeg.java
  modules/product/src/main/java/com/opengamma/strata/product/swap/RateCalculationSwapLeg.java
  modules/product/src/main/java/com/opengamma/strata/product/swap/RatePeriodSwapLeg.java
  modules/product/src/main/java/com/opengamma/strata/product/swap/Swap.java
  modules/product/src/main/java/com/opengamma/strata/product/swap/SwapLeg.java
  modules/product/src/main/java/com/opengamma/strata/product/swaption/Swaption.java
  modules/product/src/main/java/com/opengamma/strata/product/swaption/SwaptionExercise.java
  modules/product/src/test/java/com/opengamma/strata/product/swap/KnownAmountSwapLegTest.java
  modules/product/src/test/java/com/opengamma/strata/product/swap/RateCalculationSwapLegTest.java
  modules/product/src/test/java/com/opengamma/strata/product/swap/RatePeriodSwapLegTest.java
  modules/product/src/test/java/com/opengamma/strata/product/swap/SwapTest.java
  modules/product/src/test/java/com/opengamma/strata/product/swaption/SwaptionExerciseTest.java
  modules/product/src/test/java/com/opengamma/strata/product/swaption/SwaptionTest.java
Labels: Type:Enhancement

#2357 FpML for swaption Bermudan/American exercise
  modules/loader/src/main/java/com/opengamma/strata/loader/fpml/FpmlDocument.java
  modules/loader/src/main/java/com/opengamma/strata/loader/impl/fpml/SwaptionFpmlParserPlugin.java
  modules/loader/src/test/java/com/opengamma/strata/loader/fpml/FpmlDocumentParserTest.java
  modules/loader/src/test/resources/com/opengamma/strata/loader/fpml/ird-ex14-berm-swaption.xml
  modules/loader/src/test/resources/com/opengamma/strata/loader/fpml/ird-ex15-amer-swaption.xml
  modules/product/src/main/java/com/opengamma/strata/product/swaption/Swaption.java
  modules/product/src/test/java/com/opengamma/strata/product/swaption/SwaptionTest.java
Labels: Type:Enhancement

#2363 Add find methods for caplet/floorlet amount beans
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/IborCapletFloorletPeriodAmounts.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/IborCapletFloorletPeriodCurrencyAmounts.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/IborCapletFloorletPeriodAmountsTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/IborCapletFloorletPeriodCurrencyAmountsTest.java
Labels: auto-merge
