Repository OpenGamma/Strata, pull requests merged in 2022-09, with the labels that each got.

#2513 NDF Pricing: correction to currency exposure
  modules/pricer/src/main/java/com/opengamma/strata/pricer/fx/DiscountingFxNdfProductPricer.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/fx/DiscountingFxNdfProductPricerTest.java
Labels: Type:Bug

#2508 Options on ON futures: pricer
  modules/pricer/src/main/java/com/opengamma/strata/pricer/index/NormalOvernightFutureOptionExpirySimpleMoneynessVolatilities.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/index/NormalOvernightFutureOptionMarginedProductPricer.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/index/NormalOvernightFutureOptionVolatilities.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/index/OvernightFutureOptionSensitivity.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/index/OvernightFutureOptionVolatilities.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/index/OvernightFutureOptionVolatilitiesName.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/index/NormalOvernightFutureOptionExpirySimpleMoneynessVolatilitiesTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/index/NormalOvernightFutureOptionMarginedProductPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/index/OvernightFutureDummyData.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/index/OvernightFutureOptionSensitivityTest.java
Labels: Type:Enhancement

#2516 Zhengzhou commodity exchange constant added
  modules/product/src/main/java/com/opengamma/strata/product/common/ExchangeIds.java
Labels: auto-merge

#2519 Revert enforcer to fix releases
  modules/pom.xml
Labels: Status:Fixed, Type:Bug, auto-merge

#2520 Fixed Java Doc on DayCounts enum
  modules/basics/src/main/java/com/opengamma/strata/basics/date/DayCounts.java
Labels: Status:Fixed, Type:Bug, auto-merge
