Repository OpenGamma/Strata, pull requests merged in 2022-01, with the labels that each got.

#2383 Adding term rates descriptions for GBP, JPY and USD.
  modules/basics/src/main/java/com/opengamma/strata/basics/index/IborIndex.java
  modules/basics/src/main/resources/META-INF/com/opengamma/strata/config/base/FloatingRateNameData.ini
  modules/basics/src/main/resources/META-INF/com/opengamma/strata/config/base/IborIndexData.csv
  modules/basics/src/test/java/com/opengamma/strata/basics/index/IborIndexTest.java
Labels: auto-merge

#2401 Add methods to encode/decode common codecs
  modules/collect/src/main/java/com/opengamma/strata/collect/io/ArrayByteSource.java
  modules/collect/src/main/java/com/opengamma/strata/collect/io/ByteSourceCodec.java
  modules/collect/src/test/java/com/opengamma/strata/collect/io/ByteSourceCodecTest.java
Labels: auto-merge

#2385 Avoid NullPointer exception when forward is close to zero in CmsIntegrantProvider
  modules/pricer/src/main/java/com/opengamma/strata/pricer/cms/SabrExtrapolationReplicationCmsPeriodPricer.java
Labels: Type:Bug

#2365 Adjust Act/Act ICMA day count
  modules/basics/src/main/java/com/opengamma/strata/basics/date/StandardDayCounts.java
  modules/basics/src/test/java/com/opengamma/strata/basics/date/DayCountTest.java
Labels: Type:Enhancement, auto-merge

#2411 Expose getAccrualBusinessDayAdjustment() in FloatRateSwapLegConvention
  modules/product/src/main/java/com/opengamma/strata/product/swap/type/FloatRateSwapLegConvention.java
  modules/product/src/main/java/com/opengamma/strata/product/swap/type/IborRateSwapLegConvention.java
  modules/product/src/main/java/com/opengamma/strata/product/swap/type/OvernightRateSwapLegConvention.java
Labels: Type:Enhancement, auto-merge

#2410 Pricers for overnight in-arrears cap/floor.
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/SabrOvernightInArrearsCapletFloorletPeriodPricer.java
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/VolatilityOvernightInArrearsCapletFloorletPeriodPricer.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/BlackOvernightInArrearsCapletFloorletPeriodPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/IborCapletFloorletDataSet.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/IborCapletFloorletSabrRateVolatilityDataSet.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/SabrIborCapletFloorletPeriodPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/SabrOvernightInArrearsCapletFloorletPeriodPricerTest.java
  modules/product/src/main/java/com/opengamma/strata/product/capfloor/OvernightInArrearsCapletFloorletPeriod.java
  modules/product/src/test/java/com/opengamma/strata/product/capfloor/OvernightInArrearsCapletFloorletPeriodTest.java
Labels: Type:Enhancement
