Repository OpenGamma/Strata, pull requests merged in 2022-05, with the labels that each got.

#2443 Overnight in-arrears binary caplet
  modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/VerticalSpreadSabrOvernightInArrearsCapletFloorletBinaryPeriodPricer.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/VerticalSpreadSabrOvernightInArrearsCapletFloorletBinaryPeriodPricerTest.java
  modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/VerticalSpreadVolatilityIborCapletFloorletBinaryPeriodPricerTest.java
  modules/product/src/main/java/com/opengamma/strata/product/capfloor/OvernightInArrearsCapletFloorletBinaryPeriod.java
  modules/product/src/test/java/com/opengamma/strata/product/capfloor/OvernightInArrearsCapletFloorletBinaryPeriodTest.java
Labels: Type:Enhancement

#2455 Add static Nodal exchange ID
  modules/product/src/main/java/com/opengamma/strata/product/common/ExchangeIds.java
Labels: auto-merge

#2457 Enhance parse exceptions
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/CdsTradeCsvPlugin.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/CsvParseException.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/FixingSeriesCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/FraTradeCsvPlugin.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/FullSwapTradeCsvPlugin.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/FxNdfTradeCsvPlugin.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/FxRatesCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/FxSingleTradeCsvPlugin.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/IborCapFloorTradeCsvPlugin.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/LegalEntityRatesCurvesCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/PositionCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/QuotesCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/RatesCalibrationCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/RatesCurveGroupDefinitionCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/RatesCurvesCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/SeasonalityDefinitionCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/SensitivityCsvInfoResolver.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/SensitivityCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/SwapTradeCsvPlugin.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/TermDepositTradeCsvPlugin.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/TradeCsvLoader.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/FixingSeriesCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/FxRatesCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/LegalEntityRatesCurvesCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/PositionCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/QuotesCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/RatesCalibrationCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/RatesCurvesCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/SensitivityCsvLoaderTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/csv/TradeCsvLoaderTest.java
Labels: Type:Enhancement

#2458 Add Decimal class
  modules/collect/src/main/java/com/opengamma/strata/collect/Decimal.java
  modules/collect/src/test/java/com/opengamma/strata/collect/DecimalTest.java
Labels: Type:Enhancement

#2459 Use Decimal class
  modules/basics/src/main/java/com/opengamma/strata/basics/currency/Currency.java
  modules/basics/src/main/java/com/opengamma/strata/basics/currency/FxRateProvider.java
  modules/basics/src/main/java/com/opengamma/strata/basics/value/NoRounding.java
  modules/basics/src/main/java/com/opengamma/strata/basics/value/Rounding.java
  modules/basics/src/test/java/com/opengamma/strata/basics/currency/CurrencyTest.java
  modules/basics/src/test/java/com/opengamma/strata/basics/currency/FxRateTest.java
  modules/basics/src/test/java/com/opengamma/strata/basics/value/HalfUpRoundingTest.java
  modules/basics/src/test/java/com/opengamma/strata/basics/value/NoRoundingTest.java
  modules/collect/src/main/java/com/opengamma/strata/collect/Decimal.java
  modules/collect/src/main/java/com/opengamma/strata/collect/io/CsvOutput.java
  modules/collect/src/test/java/com/opengamma/strata/collect/DecimalTest.java
  modules/loader/src/main/java/com/opengamma/strata/loader/LoaderUtils.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/CsvLoaderUtils.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/RatesCurvesCsvLoader.java
  modules/loader/src/main/java/com/opengamma/strata/loader/csv/SensitivityCsvWriter.java
  modules/loader/src/test/java/com/opengamma/strata/loader/LoaderUtilsTest.java
Labels: Type:Enhancement

#2461 Convert Money and BigMoney to use Decimal
  modules/basics/src/main/java/com/opengamma/strata/basics/currency/BigMoney.java
  modules/basics/src/main/java/com/opengamma/strata/basics/currency/Money.java
  modules/basics/src/test/java/com/opengamma/strata/basics/currency/BigMoneyTest.java
  modules/basics/src/test/java/com/opengamma/strata/basics/currency/MoneyTest.java
  modules/collect/src/main/java/com/opengamma/strata/collect/Decimal.java
  modules/collect/src/test/java/com/opengamma/strata/collect/DecimalTest.java
  modules/loader/src/test/java/com/opengamma/strata/loader/LoaderUtilsTest.java
Labels: Type:Enhancement

#2462 Add Guavate map combinations
  modules/collect/src/main/java/com/opengamma/strata/collect/Guavate.java
  modules/collect/src/test/java/com/opengamma/strata/collect/GuavateTest.java
Labels: Type:Enhancement, auto-merge

#2463 Ensure that Decimal matches BigDecimal
  modules/collect/src/test/java/com/opengamma/strata/collect/DecimalTest.java
Labels: Type:Enhancement

#2465 Add Decimal.parse()
  modules/collect/src/main/java/com/opengamma/strata/collect/Decimal.java
  modules/collect/src/test/java/com/opengamma/strata/collect/DecimalTest.java
Labels: Type:Enhancement, auto-merge

#2467 Add FixedScaleDecimal
  modules/basics/src/main/java/com/opengamma/strata/basics/currency/BigMoney.java
  modules/basics/src/main/java/com/opengamma/strata/basics/currency/Money.java
  modules/basics/src/test/java/com/opengamma/strata/basics/currency/MoneyTest.java
  modules/collect/src/main/java/com/opengamma/strata/collect/Decimal.java
  modules/collect/src/main/java/com/opengamma/strata/collect/FixedScaleDecimal.java
  modules/collect/src/test/java/com/opengamma/strata/collect/DecimalTest.java
  modules/collect/src/test/java/com/opengamma/strata/collect/FixedScaleDecimalTest.java
Labels: Type:Enhancement, auto-merge

#2466 Add InvalidArgFailureException
  modules/collect/src/main/java/com/opengamma/strata/collect/result/IllegalArgFailureException.java
  modules/collect/src/test/java/com/opengamma/strata/collect/result/IllegalArgFailureExceptionTest.java
Labels: Type:Enhancement, auto-merge

#2469 Backwards compatibility
  modules/collect/pom.xml
  modules/collect/src/main/java/com/opengamma/strata/collect/io/ArrayByteSource.java
  modules/collect/src/main/java/com/opengamma/strata/collect/io/BeanByteSource.java
  modules/collect/src/main/java/com/opengamma/strata/collect/io/CharSources.java
  modules/collect/src/main/java/com/opengamma/strata/collect/io/ResourceLocator.java
  modules/pom.xml
Labels: Type:Task, auto-merge

#2470 Fix FixedScaleDecimal parsing
  modules/collect/src/main/java/com/opengamma/strata/collect/FixedScaleDecimal.java
  modules/collect/src/test/java/com/opengamma/strata/collect/FixedScaleDecimalTest.java
  modules/product/src/main/java/com/opengamma/strata/product/common/SummarizerUtils.java
Labels: Type:Bug
